[package]
name = "hexer"
version = "0.1.0"
description = "View binary files' contents in different modes"
authors = ["Vivekanandan Muthaiyan <vivekmuthu1910@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
